apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: devops-3tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:16-alpine
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: tasksdb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin123

          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: init-script
          configMap:
            name: database-init

        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: devops-3tier
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432